name: CI/CD for master branch
on: [push, pull_request]
permissions:
  contents: read

jobs:
  mix_test:
    name: Build and Test (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
    strategy:
      matrix:
        include:
          - elixir: 1.11.4
            otp: 21.3.8
          - elixir: 1.11.4
            otp: 22.3.4
          - elixir: 1.12.3
            otp: 23.3.4
          - elixir: 1.13.4
            otp: 24.3.4
          - elixir: 1.14.5
            otp: 25.3.2
          - elixir: 1.16.2
            otp: 26.2.3
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore deps and _build cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - name: Install dependencies
        run: mix deps.get --only test
      - name: Run tests
        run: mix test
